services:

  mediacms:
    image: mediacms/mediacms:latest
    container_name: mediacms
    ports:
      - 5454:80
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - M:\\mediacms:/home/mediacms.io/mediacms/media_files
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      PORTAL_NAME: 'Sleeplessness'
      REDIS_LOCATION: 'redis://host.docker.internal:6379/1'
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESSNESS_SECRET_KEY}'
    depends_on:
      - migrations
    restart: unless-stopped
    labels:
      virtual.host: sleeplessness.${DOMAIN}
      virtual.port: 80
      virtual.tls-email: ${TLS_EMAIL}
      homepage.group: Media
      homepage.name: Sleeplessness
      homepage.icon: /icons/sleeplessness.png
      homepage.href: https://sleeplessness.${DOMAIN}
      homepage.description: Collection of animation films
      
  celery_beat:
    image: mediacms/mediacms:latest
    container_name: celery_beat
    volumes_from:
      - mediacms:rw
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      PORTAL_NAME: 'Sleeplessness'
      REDIS_LOCATION: 'redis://host.docker.internal:6379/1'
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESSNESS_SECRET_KEY}'
    restart: unless-stopped
    
  celery:
    image: mediacms/mediacms:latest
    container_name: celery
    volumes_from:
      - mediacms:rw
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
      PORTAL_NAME: 'Sleeplessness'
      REDIS_LOCATION: 'redis://host.docker.internal:6379/1'
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESSNESS_SECRET_KEY}'
    depends_on:
      - migrations
    restart: unless-stopped

  migrations:
    image: mediacms/mediacms:latest
    container_name: migrations
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: '${SLEEPLESSNESS_ADMIN_USER}'
      ADMIN_EMAIL: '${SLEEPLESSNESS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${SLEEPLESSNESS_ADMIN_PASSWORD}'
      PORTAL_NAME: 'Sleeplessness'
      REDIS_LOCATION: 'redis://host.docker.internal:6379/1'
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESSNESS_SECRET_KEY}'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure