# On error 
# exec ./deploy/docker/entrypoint.sh: no such file or directory
# Change *.sh files in ./deploy/docker CRLF to LF 

services:

  mediacms:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mediacms
    networks:
      - server_default
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - M:\\mediacms:/home/mediacms.io/mediacms/media_files
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      PORTAL_NAME: 'Sleepless'
      REDIS_LOCATION: 'redis://redis:6379/1'
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESS_SECRET_KEY}'
    depends_on:
      - migrations
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sleepless.rule: Host(`sleepless.${DOMAIN}`)
      traefik.http.routers.sleepless.entrypoints: websecure
      traefik.http.routers.sleepless.tls.certresolver: letsencrypt
      traefik.http.services.sleepless.loadbalancer.server.port: 80
      homepage.group: Media
      homepage.name: Sleepless
      homepage.icon: /icons/sleepless.png
      homepage.href: https://sleepless.${DOMAIN}
      homepage.description: Collection of animation films
      
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-beat
    networks:
      - server_default
    volumes_from:
      - mediacms:rw
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      PORTAL_NAME: 'Sleepless'
      REDIS_LOCATION: 'redis://redis:6379/1'
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESS_SECRET_KEY}'
    restart: unless-stopped
    labels:
      homepage.group: Containers
      homepage.name: Celery-beat
      homepage.icon: /icons/sleepless.png
      
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    networks:
      - server_default
    volumes_from:
      - mediacms:rw
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
      PORTAL_NAME: 'Sleepless'
      REDIS_LOCATION: 'redis://redis:6379/1'
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESS_SECRET_KEY}'
    depends_on:
      - migrations
    restart: unless-stopped
    labels:
      homepage.group: Containers
      homepage.name: Celery
      homepage.icon: /icons/sleepless.png

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrations    
    networks:
      - server_default
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: '${SLEEPLESS_ADMIN_USER}'
      ADMIN_EMAIL: '${SLEEPLESS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${SLEEPLESS_ADMIN_PASSWORD}'
      PORTAL_NAME: 'Sleepless'
      REDIS_LOCATION: 'redis://redis:6379/1'
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SECRET_KEY: '${SLEEPLESS_SECRET_KEY}'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
 
networks:
  server_default:
    external: true
    name: server_default